config/routes.rb
R::Application.routes.draw do
  resources :videos

  root :to => 'videos#new'

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :end_time, :start_time, :youtube_id, :name

  validates_presence_of :end_time, :start_time, :youtube_id, :name

  default_scope order: 'created_at DESC'


  def start_str
    format_time(start_time)
  end

  def end_str
    format_time(end_time)
  end


  def format_time(total_seconds, options = {})
    seconds = total_seconds % 60
    minutes = (total_seconds / 60) % 60
    hours = total_seconds / 3600

    if hours > 0
      "%d:%02d:%02d" % [hours, minutes, seconds]
    else
      "%d:%02d" % [minutes, seconds]
    end
  end

  # Helper method to parse a string like "1:03:56.555" and return the number of
  # milliseconds that time length represents.
  def parse_time(string)
    parts = string.split(":").map(&:to_f)
    parts = [0] + parts if parts.length == 2
    hours, minutes, seconds = parts
    seconds = hours * 3600 + minutes * 60 + seconds
    seconds.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.paginate(:per_page => 10, :page => params[:page])
  end

  def new
    @video = Video.new
    @title = "Create new video"
  end

  def create
    @video = Video.new(params[:video])
    if @video.save
      flash[:success] = "Created Video!"
      redirect_to @video
    else
      @title = "Create new video"
      render 'new'
    end
  end

  def show
    @video = Video.find(params[:id])
    @name = @video.name
    @youtube_id = @video.youtube_id
    @start_time = @video.start_time
    @end_time = @video.end_time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/videos_helper.rb
module VideosHelper
  def youtube_embed_html(video_id, start_time, end_time)
    content_tag(:iframe, :src => "http://www.youtube.com/embed/#{video_id}?start=#{start_time}&end=#{end_time}".html_safe,
                :width => "480", 
                :height => "270", 
                :frameborder => "0",
                :class => "ytplayerframe") do
    end
  end

  def youtube_hidden_embed_html(youtube_id, start_time, end_time)
    content_tag(:iframe, :src => "http://www.youtube.com/embed/#{youtube_id}?start=#{start_time}&end=#{end_time}&autoplay=1&autohide=2&controls=0&showinfo=0".html_safe,
                :width => "640", :height => "360", :frameborder => "0") do
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Roller", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= mail_to 'contactroller@gmail.com', "Contact"%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="row">
	<div class="span4">
		<ul class="nav nav-pills ">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Videos", videos_path %></li>
			<li><%= link_to "Help",    '#' %></li>
		</ul>
	</div>
	<h1 class='logo span4'><em>Roller</em></h1>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roller</title>
  <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css">
  
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "http://www.google.com/jsapi" %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>    
</head>
<body>


  <div class="container">
    <div>
      <%= render 'layouts/header' %>
    </div>
    <hr>
    <div class="content">
     <%= yield %>
   </div>
   <%= render 'layouts/footer' %>
 </div>

</body>
</html>

app/views/videos/_video.html.erb
<li class="video-item">
  <h4><%= link_to video.name, video_path(video.id) %></h4>
  <p>
    <span class="timestamp">
    Posted <%= time_ago_in_words(video.created_at) %> ago.
  	</span>
  </p>

  <%= raw youtube_embed_html(video.youtube_id, video.start_time, video.end_time) %>
  <!-- <span class="video_id">ID: <%= video.id %></span> -->
</li>

app/views/videos/create.html.erb
<h1>Video#create</h1>
<p>Find me in app/views/video/create.html.erb</p>

app/views/videos/index.html.erb
	<ol class="videos">
		<%= render @videos %>
	</ol>

	<%= will_paginate @videos, :class => 'pagination pagination-centered' %>

app/views/videos/new.html.erb
<div class="row">   
  <div class="span12">

    <div class="row">
        <div class="offset2">
          <div class="controls controls-row" id="video-loader">
            <input class="span6" id="youtube_url" type="text" value="http://www.youtube.com/watch?v=DE9NsrKzSq8" >
            <button class="btn span2 load" type='text' id="load-video">Load Video</button>
          </div>
        </div>
        
      </div>


      <div class="row">
        <div id="video" class="span8 offset2"></div>
      </div>

      <div class="row">
        <div class="span8 offset2">
          <div id="slider"></div>
        </div>
      </div> <!-- end row -->


      <div class="row" id='controls'>       
        <div id="buttons" class="span2 offset4">
          <div class="row">
            <button class='play btn btn-large' ><i class="icon-play"></i></button>
            <button class='restart btn btn-large ' ><i class="icon-repeat"></i></button>
          </div>

        </div>
        <span id='info' class='span4'>
          Start: <span class="start-time">--:--</span> <br>
          Current: <span class="current-time">--:--</span> <br>
          End: <span class="end-time">--:--</span>
        </span>

      </div> <!-- end row -->

      <div class="row">
        <div class="offset2">
          <%= form_for @video do |f| %>
          <%= f.hidden_field :youtube_id, :value => "DE9NsrKzSq8" %>
          <%= f.hidden_field :start_time, :value => 470 %>
          <%= f.hidden_field :end_time, :value => 475 %>
          <div class="controls controls-row">
            <%= f.text_field :name, :placeholder => "Give your clip a name", :class => "span4" %>
            <%= f.submit 'Create Clip', :class => 'btn btn-primary span4 ' %>
          </div>
          <% end %>
        </div>
      </div>



  </div>
</div>

app/views/videos/show.html.erb
<div class="row">
	<div class="span8 offset2">
		<div id="videoWrapper">
			<%= youtube_hidden_embed_html(@youtube_id, @start_time, @end_time) %>
		</div>
		<h2 class='video-name'><%= @name %></h2>
		
	</div>
</div>